name: linting

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    env:
      NOXSESSION: lint
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install -U pip setuptools
          python -m pip install nox
      
      - name: Run Pylint
        run: nox
